### ISSUE TITLE
Image dont download

### ISSUE THREAD

**Issue by mhambuch** [mworion/MountWizzard4#167]
Hi Michael 

I have an issue with an Alcapa/Ascom remote server driven camera. Camera is recognized in MW4 and connected. When taking 1 exposure the image wont download. I have to abort the exposure. There is an error quoted in the log i attached.

![image](https://user-images.githubusercontent.com/63575440/129472200-0bb3e2a8-ca7a-4ec9-9226-8dc9511bc57b.png)

![image](https://user-images.githubusercontent.com/63575440/129472263-b889de3e-bfef-4fd6-9a71-886d05da4c1a.png)

![image](https://user-images.githubusercontent.com/63575440/129472288-c2c8d1ee-2c4b-4aa3-89ee-65114cb03097.png)

blocked on download

[2021-08-15 08:15:14.520][C][       tpool.py][  92] C:\Users\PrimaLuceLab\Documents\MW4\venv\Lib\site-packages\mw4\logic\imaging\cameraAlpaca.py, line 187 int() argument must be a string, a bytes-like object or a number, not 'NoneType'

[mw4-2021-08-15.log](https://github.com/mworion/MountWizzard4/files/6987764/mw4-2021-08-15.log)

**Comment by mworion** [comment]
Hi,
I revised the ascom handling with larger scale image sensors in version 2. I checked your issue with the actual beta and it should be solved. I will publish a beta (v2.0.0b40) this afternoon. If you update (it's close to release anyway) it should be solved.
To update use the script MW4_update_beta.bat to get it. From v2 on the internal updater should handle an further updates without a script.
Michel

**Comment by mhambuch** [comment]
Hi Michel

Same issue with the latest beta version.

![image](https://user-images.githubusercontent.com/63575440/129486433-36f38091-4d8f-411b-9cf1-0f4782f94dfc.png)

**Comment by mworion** [comment]
Yes, the change for dressing the issue is in v40, which is not released yet. You tested with v39, so that's true.
Michel

PS: v40 will be available in about 1h from now

**Comment by mworion** [comment]
v2.0.0b40 published

**Comment by mhambuch** [comment]
Hi Michel
Still hanging on the download

![image](https://user-images.githubusercontent.com/63575440/129516691-28ba2cf6-0894-4f89-ac5c-45c360b17991.png)
[mw4-2021-08-16.log](https://github.com/mworion/MountWizzard4/files/6990048/mw4-2021-08-16.log)

**Comment by mworion** [comment]
Hi,
I build a more deep test version v41 and uploaded it for this issue and increased the alpaca timeout value. Please raise the debug level under /settings/Misc from standard to debug and please test again.
Michel

**Comment by mhambuch** [comment]
Hi Michel

![image](https://user-images.githubusercontent.com/63575440/129524628-16cbafee-4037-4518-af2d-5eaa8bb4362c.png)
[mw4-2021-08-16.log](https://github.com/mworion/MountWizzard4/files/6990359/mw4-2021-08-16.log)

**Comment by mhambuch** [comment]
L‌atest log file i didnt manage to load it on github

 
 

De : "Michael"
A : "mworion/MountWizzard4" ,"mhambuch" ,"Author"
Envoyé: lundi 16 Août 2021 08:31
Objet : Re: [mworion/MountWizzard4] Image dont download (#167)
 

 

Hi,
I build a more deep test version v41 and uploaded it for this issue and increased the alpaca timeout value. Please raise the debug level under /settings/Misc from standard to debug and please test again.
Michel

**Comment by mworion** [comment]
HI, which size does it has ? Is it too large?
Two possibilities: Zip it or make a log only in debug, without trace.
Michel

**Comment by mhambuch** [comment]
still timeout line at timestamp 7:35:30
[mw4-2021-08-16.log](https://github.com/mworion/MountWizzard4/files/6990566/mw4-2021-08-16.log)

**Comment by mworion** [comment]
...build v42 with extending timeout and more logging. Trace mode should be ok right now (with smaller logs). Please delete the old one of today.
Michel

**Comment by mhambuch** [comment]
seems to work now!

![image](https://user-images.githubusercontent.com/63575440/129530140-4d7a33d8-2383-4e24-bbec-6b8c330a57e9.png)
[mw4-2021-08-16.log](https://github.com/mworion/MountWizzard4/files/6990662/mw4-2021-08-16.log)

**Comment by mworion** [comment]
OK, we are one step further. Please try v43 as there was a hidden topic.
Michel

**Comment by mhambuch** [comment]
YES! 

![image](https://user-images.githubusercontent.com/63575440/129531553-4038a709-f17a-4211-8c58-4f99b056cf9a.png)
[mw4-2021-08-16.log](https://github.com/mworion/MountWizzard4/files/6990706/mw4-2021-08-16.log)

**Comment by mworion** [comment]
OK, I think that was also the final clue to it (after visiting the log). Closing the issue. In case of further observations, please reopen again.
Michel

**Comment by mhambuch** [comment]
yes thanks a lot

**Comment by mworion** [comment]
Yes, MW4 is async and it's intended that processing time and slewing time could run in parallel to use time best.

**Comment by mworion** [comment]
Just on reminder: Please take care that in your setup the values for focal length and aperture are set. otherwise the plat solve has some issues in finding this right image scale in pixel / arcsec.

**Comment by mhambuch** [comment]
Thanks Michel, I have a question regarding the model names. I understand that the mount can store several models and that mw always stores those in the mount.So when i build a new model, at the end of the process i see in the log a line telling it stores it in the mount. So what name is then used as i havent saved is as ... at that time.  is it the "actual" one ? Also if i have a model that i want the mount to use i need to save it as "actual" as i understand that this is the one of current use by the mount?Is my understanding correct?Many thanks
-------- Message d'origine --------De : Michael ***@***.***> Date : 16/08/2021  10:19  (GMT+01:00) À : mworion/MountWizzard4 ***@***.***> Cc : mhambuch ***@***.***>, Author ***@***.***> Objet : Re: [mworion/MountWizzard4] Image dont download (#167) 
Just on reminder: Please take care that in your setup the values for focal length and aperture are set. otherwise the plat solve has some issues in finding this right image scale in pixel / arcsec.

**Comment by mworion** [comment]
To clarify this point:
In the mount there is only one actual model. If you build a new one, this is it. This model does not have any name in the mount. If you build a new one, it's just overwritten. 
The mount offers to store the actual model in a separate location in the mount (which is only the resulting model). There you could choose a name and you will see this models as list under /Manage Model tab lower right corner. You have to explicitly store it with a new you would like to take and could also retrieve it from the mount storage. All models in the mount are not accessible outside the mount!
MW4 itself stores automatically all necessary data for the model builds in the work directory. This might include the images taken for a model run, too. With this data, you could rebuild the model at any time again. So it's not the model itself (as it could not be retrieved from the mount), but all data to rebuild it without taking images etc.
Please bear in mind, that models (and of course the underlying model data) is invalid if you do physical changes to your setup.  So keeping many model for running them actively might not make much sense. To keep the data to compare changes over time (without using them actively) does make some sense.
Michel

**Comment by mhambuch** [comment]
All clear, makes sense. Thx
-------- Message d'origine --------De : Michael ***@***.***> Date : 16/08/2021  11:35  (GMT+01:00) À : mworion/MountWizzard4 ***@***.***> Cc : mhambuch ***@***.***>, Author ***@***.***> Objet : Re: [mworion/MountWizzard4] Image dont download (#167) 
To clarify this point:
In the mount there is only one actual model. If you build a new one, this is it. This model does not have any name in the mount. If you build a new one, it's just overwritten.
The mount offers to store the actual model in a separate location in the mount (which is only the resulting model). There you could choose a name and you will see this models as list under /Manage Model tab lower right corner. You have to explicitly store it with a new you would like to take and could also retrieve it from the mount storage. All models in the mount are not accessible outside the mount!
MW4 itself stores automatically all necessary data for the model builds in the work directory. This might include the images taken for a model run, too. With this data, you could rebuild the model at any time again. So it's not the model itself (as it could not be retrieved from the mount), but all data to rebuild it without taking images etc.
Please bear in mind, that models (and of course the underlying model data) is invalid if you do physical changes to your setup.  So keeping many model for running them actively might not make much sense. To keep the data to compare changes over time (without using them actively) does make some sense.
Michel
